// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechShowdown;

namespace TechShowdown.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20190417180158_AddPosts")]
    partial class AddPosts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechShowdown.Post", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Content");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("880200b0-21fc-4a48-8588-12f0556df6d4"),
                            Content = "Winter is coming",
                            UserId = new Guid("b32b790d-f9cb-49eb-9e7b-4e6132592084")
                        },
                        new
                        {
                            Id = new Guid("62b935d6-6d3e-4aeb-97c9-0242645b751b"),
                            Content = "Hasta la vista, baby",
                            UserId = new Guid("62ad51cc-7475-48bb-b7a8-afe5631cd26f")
                        });
                });

            modelBuilder.Entity("TechShowdown.User", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b32b790d-f9cb-49eb-9e7b-4e6132592084"),
                            Name = "John Snow"
                        },
                        new
                        {
                            Id = new Guid("62ad51cc-7475-48bb-b7a8-afe5631cd26f"),
                            Name = "Sarah Connor"
                        });
                });

            modelBuilder.Entity("TechShowdown.Post", b =>
                {
                    b.HasOne("TechShowdown.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
