// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechShowdown;
using TechShowdown.DataAccess;

namespace TechShowdown.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20190416184934_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechShowdown.User", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b32b790d-f9cb-49eb-9e7b-4e6132592084"),
                            Name = "John Snow"
                        },
                        new
                        {
                            Id = new Guid("62ad51cc-7475-48bb-b7a8-afe5631cd26f"),
                            Name = "Sarah Connor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
